esphome:
  name: trmnl
  friendly_name: trmnl

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: "YOUR_SSID"
  password: "YOUR_PASSWORD"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Trmnl Fallback Hotspot"
    password: "fallback-password"

captive_portal:

# Component to make HTTP requests
http_request:
  user_agent: esphome/device

# Check for wifi connectivity
binary_sensor:
  - platform: status
    name: "Trmnl Status"

# SPI bus configuration for the Waveshare e-paper display.
# These pins are the default hardware SPI pins for the ESP32-C3.
spi:
  clk_pin: GPIO6
  mosi_pin: GPIO7

# Image component to download the dashboard image
image:
  - id: dashboard_image
    url: https://raw.githubusercontent.com/kevdog114/trmnl_ha_dash/main/trmnl.bmp
    type: Grayscale
    use_cache: false

time:
  - platform: homeassistant
    id: ha_time

# Display configuration for the Waveshare 7.5" e-paper display.
# IMPORTANT: Ensure your display is wired to the ESP32-C3-DevKitM-1 according to these pins.
display:
  - platform: waveshare_epaper
    id: epaper_display
    # Model for the Waveshare 7.5inch e-Paper Module (B) V3 with Black, White, and Red support.
    # If you have the black and white only version, use '7.50in-bV3'.
    model: 7.50in-bV3-bwr
    # The CS pin MUST be a free GPIO. GPIO10 is used for the internal flash and cannot be used.
    cs_pin: GPIO5
    dc_pin: GPIO0
    busy_pin:
      number: GPIO1
      # This is required for V2 and V3 models to prevent damage.
      inverted: true
    reset_pin: GPIO3
    update_interval: 300s
    lambda: |-
      // Clear the screen
      it.fill(it.COLOR_ON);
      // Draw the image
      it.image(0, 0, id(dashboard_image));